name: Functional tests using Ragger

on:
  workflow_call:
    inputs:
      uploaded_artifact_name:
        required: true
        type: string

jobs:
  build:
    name: Build application for NanoS, X, S+, and Stax
    strategy:
      matrix:
        include:
          - SDK: "$NANOS_SDK"
          - SDK: "$NANOX_SDK"
          - SDK: "$NANOSP_SDK"
          - SDK: "$STAX_SDK"

    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ledgerhq/ledger-app-builder/ledger-app-builder-lite:latest

    steps:
      - name: Clone
        uses: actions/checkout@v3

      - name: Build application
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          make BOLOS_SDK=${{ matrix.SDK }}

      - name: Remove build artifacts before upload
        run: |
          find ./build/*/ -mindepth 1 -type d ! -name 'bin' -exec rm -r {} +

      - name: Upload app binary
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.uploaded_artifact_name }}
          path: build/*
