name: Ensure app compliance with Ledger guidelines

on:
  workflow_call:

jobs:
  call_check_icons:
    name: Dispatch
    uses: ./.github/workflows/_check_icons.yml

  call_check_makefile:
    name: Dispatch
    uses: ./.github/workflows/_check_makefile.yml

  call_check_readme:
    name: Dispatch
    uses: ./.github/workflows/_check_readme.yml

  call_clang_static_analyzer:
    name: Dispatch
    uses: ./.github/workflows/_check_clang_static_analyzer.yml
